#server:
#  port: 3389
##  context-path: /web1.2
#web:
#  upload-path: /home/wangyu/ihome1.2/misshare/web/src/main/resources/
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wifilocation?useSSL=true
#    username: root
#    password: 950820
#    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    schema: classpath:h2sqlForTest/schema.sql
#    data: classpath:h2sqlForTest/data.sql
#  jpa:
#    hibernate:
#      ddl-auto: update
